//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB_Explorer.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADB_Explorer.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string S_ACTION_HIDE {
            get {
                return ResourceManager.GetString("S_ACTION_HIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download ADB.
        /// </summary>
        public static string S_ADB_DOWNLOAD {
            get {
                return ResourceManager.GetString("S_ADB_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB Executable.
        /// </summary>
        public static string S_ADB_EXECUTABLE {
            get {
                return ResourceManager.GetString("S_ADB_EXECUTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More About ADB.
        /// </summary>
        public static string S_ADB_LEARN_MORE {
            get {
                return ResourceManager.GetString("S_ADB_LEARN_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB version from provided path is too low..
        /// </summary>
        public static string S_ADB_VERSION_LOW_OVERRIDE {
            get {
                return ResourceManager.GetString("S_ADB_VERSION_LOW_OVERRIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring File Explorer enables the app to perform Drag / Clipboard Pull operations directly to the destination folder.
        ///
        ///Otherwise, Pull is performed to the app temp folder, from which File Explorer receives the file as a stream, which has to use a small buffer.
        ///These two added steps slow down the process significantly.
        ///
        ///The feature is auto-disabled for other selected file managers..
        /// </summary>
        public static string S_ADVANCED_DRAG {
            get {
                return ResourceManager.GetString("S_ADVANCED_DRAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable only if you intend to use the app with File Explorer.
        ///You can always change this in the settings..
        /// </summary>
        public static string S_ADVANCED_DRAG_SPLASH {
            get {
                return ResourceManager.GetString("S_ADVANCED_DRAG_SPLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Explorer Monitoring.
        /// </summary>
        public static string S_ADVANCED_DRAG_TITLE {
            get {
                return ResourceManager.GetString("S_ADVANCED_DRAG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Android Robot Icon(s).
        /// </summary>
        public static string S_ANDROID_ICONS_TITLE {
            get {
                return ResourceManager.GetString("S_ANDROID_ICONS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Android robot is reproduced or modified from work created and shared by Google and used according to terms described in the Creative Commons 3.0 Attribution License..
        /// </summary>
        public static string S_ANDROID_ROBOT_LIC {
            get {
                return ResourceManager.GetString("S_ANDROID_ROBOT_LIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Animations.
        /// </summary>
        public static string S_ANIMATION_TITLE {
            get {
                return ResourceManager.GetString("S_ANIMATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The APK icon is licensed under the Apache License, Version 2.0..
        /// </summary>
        public static string S_APK_ICON_LIC {
            get {
                return ResourceManager.GetString("S_APK_ICON_LIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Data Folder.
        /// </summary>
        public static string S_APP_DATA_FOLDER {
            get {
                return ResourceManager.GetString("S_APP_DATA_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributions &amp; Third Party Licenses.
        /// </summary>
        public static string S_ATTRIBUTIONS {
            get {
                return ResourceManager.GetString("S_ATTRIBUTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string S_BUTTON_CHANGE {
            get {
                return ResourceManager.GetString("S_BUTTON_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string S_BUTTON_CLEAR {
            get {
                return ResourceManager.GetString("S_BUTTON_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string S_BUTTON_CLOSE {
            get {
                return ResourceManager.GetString("S_BUTTON_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string S_BUTTON_CONTINUE_TOOLTIP {
            get {
                return ResourceManager.GetString("S_BUTTON_CONTINUE_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string S_BUTTON_MORE_INFO_TOOLTIP {
            get {
                return ResourceManager.GetString("S_BUTTON_MORE_INFO_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string S_CANCEL {
            get {
                return ResourceManager.GetString("S_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Commons.
        /// </summary>
        public static string S_CC_NAME {
            get {
                return ResourceManager.GetString("S_CC_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string S_COLLAPSE_ALL {
            get {
                return ResourceManager.GetString("S_COLLAPSE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Uninstall.
        /// </summary>
        public static string S_CONF_UNI_TITLE {
            get {
                return ResourceManager.GetString("S_CONF_UNI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string S_CONFIRM {
            get {
                return ResourceManager.GetString("S_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is 1 conflicting item.
        /// </summary>
        public static string S_CONFLICT_ITEMS {
            get {
                return ResourceManager.GetString("S_CONFLICT_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is 1 conflicting item in {0}.
        /// </summary>
        public static string S_CONFLICT_ITEMS_DESTINATION {
            get {
                return ResourceManager.GetString("S_CONFLICT_ITEMS_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} conflicting items.
        /// </summary>
        public static string S_CONFLICT_ITEMS_PLURAL {
            get {
                return ResourceManager.GetString("S_CONFLICT_ITEMS_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} conflicting items in {1}.
        /// </summary>
        public static string S_CONFLICT_ITEMS_PLURAL_DESTINATION {
            get {
                return ResourceManager.GetString("S_CONFLICT_ITEMS_PLURAL_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Explorer monitoring is not available due to the following apps running:.
        /// </summary>
        public static string S_CONFLICTING_APPS {
            get {
                return ResourceManager.GetString("S_CONFLICTING_APPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting Apps.
        /// </summary>
        public static string S_CONFLICTING_APPS_TITLE {
            get {
                return ResourceManager.GetString("S_CONFLICTING_APPS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Package Name.
        /// </summary>
        public static string S_COPY_APK_NAME {
            get {
                return ResourceManager.GetString("S_COPY_APK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Item Path.
        /// </summary>
        public static string S_COPY_PATH {
            get {
                return ResourceManager.GetString("S_COPY_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Error.
        /// </summary>
        public static string S_CREATE_ERR_TITLE {
            get {
                return ResourceManager.GetString("S_CREATE_ERR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string S_DEL_CONF_TITLE {
            get {
                return ResourceManager.GetString("S_DEL_CONF_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string S_DELETE_ACTION {
            get {
                return ResourceManager.GetString("S_DELETE_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following will be deleted:
        ///{0}.
        /// </summary>
        public static string S_DELETE_CONFIRMATION {
            get {
                return ResourceManager.GetString("S_DELETE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following will be permanently deleted:
        ///{0}.
        /// </summary>
        public static string S_DELETE_PERMANENT {
            get {
                return ResourceManager.GetString("S_DELETE_PERMANENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A helper program for reading push/pull progress from ADB..
        /// </summary>
        public static string S_DEPLOY_REDIRECTION {
            get {
                return ResourceManager.GetString("S_DEPLOY_REDIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Might falsely trigger some anti-virus programs..
        /// </summary>
        public static string S_DEPLOY_REDIRECTION_ARM {
            get {
                return ResourceManager.GetString("S_DEPLOY_REDIRECTION_ARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deploy executable.
        ///Disk usage progress method will be used instead..
        /// </summary>
        public static string S_DEPLOY_REDIRECTION_ERROR {
            get {
                return ResourceManager.GetString("S_DEPLOY_REDIRECTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy AdbProgressRedirection.exe.
        /// </summary>
        public static string S_DEPLOY_REDIRECTION_TITLE {
            get {
                return ResourceManager.GetString("S_DEPLOY_REDIRECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to %LocalAppData%\AdbExplorer.
        /// </summary>
        public static string S_DEPLOY_REDIRECTION_x64 {
            get {
                return ResourceManager.GetString("S_DEPLOY_REDIRECTION_x64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Path Error.
        /// </summary>
        public static string S_DEST_ERR {
            get {
                return ResourceManager.GetString("S_DEST_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app has many animations that are enabled as part of the fluent design.
        ///The side views animation is always disabled when the app window is maximized on a secondary display.
        ///
        ///• Checking this setting disables all app animations except progress bars, progress rings, and drive usage bars..
        /// </summary>
        public static string S_DISABLE_ANIMATION {
            get {
                return ResourceManager.GetString("S_DISABLE_ANIMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB server needs to be restarted in order to disable mDNS..
        /// </summary>
        public static string S_DISABLE_MDNS {
            get {
                return ResourceManager.GetString("S_DISABLE_MDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable mDNS.
        /// </summary>
        public static string S_DISABLE_MDNS_TITLE {
            get {
                return ResourceManager.GetString("S_DISABLE_MDNS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string S_DISABLED {
            get {
                return ResourceManager.GetString("S_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnection Error.
        /// </summary>
        public static string S_DISCONN_FAILED_TITLE {
            get {
                return ResourceManager.GetString("S_DISCONN_FAILED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push/pull progress is displayed in total bytes transferred.
        ///Percentage is available only when total size is known..
        /// </summary>
        public static string S_DISK_USAGE_PROGRESS {
            get {
                return ResourceManager.GetString("S_DISK_USAGE_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Usage Only.
        /// </summary>
        public static string S_DISK_USAGE_PROGRESS_TITLE {
            get {
                return ResourceManager.GetString("S_DISK_USAGE_PROGRESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate or Sponsor.
        /// </summary>
        public static string S_DONATE {
            get {
                return ResourceManager.GetString("S_DONATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Recycle Bin.
        /// </summary>
        public static string S_EMPTY_TRASH {
            get {
                return ResourceManager.GetString("S_EMPTY_TRASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string S_ENABLED {
            get {
                return ResourceManager.GetString("S_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Search.
        /// </summary>
        public static string S_EXIT_SEARCH {
            get {
                return ResourceManager.GetString("S_EXIT_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        public static string S_EXPAND_ALL {
            get {
                return ResourceManager.GetString("S_EXPAND_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to override ADB.
        /// </summary>
        public static string S_FAIL_OVERRIDE_TITLE {
            get {
                return ResourceManager.GetString("S_FAIL_OVERRIDE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to connect to.
        /// </summary>
        public static string S_FAILED_CONN {
            get {
                return ResourceManager.GetString("S_FAILED_CONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string S_FAILED_CONN_TITLE {
            get {
                return ResourceManager.GetString("S_FAILED_CONN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Operations.
        /// </summary>
        public static string S_FILE_OP_TOOLTIP {
            get {
                return ResourceManager.GetString("S_FILE_OP_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUSE drive.
        ///• Symbolic links are not supported
        ///• File names cannot contain &quot; * / : &lt; &gt; ? \ |
        ///• File names are case insensitive
        ///• Installation of APKs is not supported.
        /// </summary>
        public static string S_FUSE_DRIVE_TOOLTIP {
            get {
                return ResourceManager.GetString("S_FUSE_DRIVE_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub repository.
        /// </summary>
        public static string S_GITHUB_REPO {
            get {
                return ResourceManager.GetString("S_GITHUB_REPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Release Notes.
        /// </summary>
        public static string S_GO_TO_RELEASE_NOTES {
            get {
                return ResourceManager.GetString("S_GO_TO_RELEASE_NOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Version Page.
        /// </summary>
        public static string S_GO_TO_VERSION_PAGE {
            get {
                return ResourceManager.GetString("S_GO_TO_VERSION_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is a UI for ADB - Android Debug Bridge.
        ///To use the app, you need to have ADB on your PC.
        ///ADB is available as part of the Android SDK Platform Tools.
        ///You can use the provided link to download the SDK Platform Tools.
        ///Unfortunately, we cannot provide ADB with the app due to licensing restrictions..
        /// </summary>
        public static string S_HELP_ON_ADB {
            get {
                return ResourceManager.GetString("S_HELP_ON_ADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help On ADB.
        /// </summary>
        public static string S_HELP_ON_ADB_TITLE {
            get {
                return ResourceManager.GetString("S_HELP_ON_ADB_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select packages to install.
        /// </summary>
        public static string S_INSTALL_APK {
            get {
                return ResourceManager.GetString("S_INSTALL_APK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination for {0}.
        /// </summary>
        public static string S_ITEM_DESTINATION {
            get {
                return ResourceManager.GetString("S_ITEM_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination for multiple items.
        /// </summary>
        public static string S_ITEM_DESTINATION_PLURAL {
            get {
                return ResourceManager.GetString("S_ITEM_DESTINATION_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to kill this emulator?.
        /// </summary>
        public static string S_KILL_EMULATOR {
            get {
                return ResourceManager.GetString("S_KILL_EMULATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill {0}.
        /// </summary>
        public static string S_KILL_EMULATOR_TITLE {
            get {
                return ResourceManager.GetString("S_KILL_EMULATOR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate ADB (v{0} at least):.
        /// </summary>
        public static string S_LOCATE_ADB_TITLE {
            get {
                return ResourceManager.GetString("S_LOCATE_ADB_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to list the contents of this folder.
        ///Visible content may be incomplete..
        /// </summary>
        public static string S_LS_ERROR {
            get {
                return ResourceManager.GetString("S_LS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Directory Error.
        /// </summary>
        public static string S_LS_ERROR_TITLE {
            get {
                return ResourceManager.GetString("S_LS_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge or Replace.
        /// </summary>
        public static string S_MERGE_OR_REPLACE {
            get {
                return ResourceManager.GetString("S_MERGE_OR_REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get ADB version from provided path..
        /// </summary>
        public static string S_MISSING_ADB_OVERRIDE {
            get {
                return ResourceManager.GetString("S_MISSING_ADB_OVERRIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Error.
        /// </summary>
        public static string S_NAV_ERR_TITLE {
            get {
                return ResourceManager.GetString("S_NAV_ERR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair and/or connect a WiFi device (without using mDNS).
        /// </summary>
        public static string S_NEW_DEVICE_TIP {
            get {
                return ResourceManager.GetString("S_NEW_DEVICE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string S_NEW_FOLDER {
            get {
                return ResourceManager.GetString("S_NEW_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        public static string S_NEW_ITEM {
            get {
                return ResourceManager.GetString("S_NEW_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new {0}, version {1}, is available.
        /// </summary>
        public static string S_NEW_VERSION {
            get {
                return ResourceManager.GetString("S_NEW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to a new ADB Explorer version!
        ///The release notes are available on GitHub..
        /// </summary>
        public static string S_NEW_VERSION_MSG {
            get {
                return ResourceManager.GetString("S_NEW_VERSION_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New App Version.
        /// </summary>
        public static string S_NEW_VERSION_TITLE {
            get {
                return ResourceManager.GetString("S_NEW_VERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ADB Executable.
        /// </summary>
        public static string S_OVERRIDE_ADB_BROWSE {
            get {
                return ResourceManager.GetString("S_OVERRIDE_ADB_BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairing Error.
        /// </summary>
        public static string S_PAIR_ERR_TITLE {
            get {
                return ResourceManager.GetString("S_PAIR_ERR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an ancestor of the destination folder..
        /// </summary>
        public static string S_PASTE_ANCESTOR {
            get {
                return ResourceManager.GetString("S_PASTE_ANCESTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Conflicts.
        /// </summary>
        public static string S_PASTE_CONFLICTS_TITLE {
            get {
                return ResourceManager.GetString("S_PASTE_CONFLICTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently Delete.
        /// </summary>
        public static string S_PERM_DEL {
            get {
                return ResourceManager.GetString("S_PERM_DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [not set].
        /// </summary>
        public static string S_PLACEHOLDER_NOT_SET {
            get {
                return ResourceManager.GetString("S_PLACEHOLDER_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string S_PRIVACY_POLICY {
            get {
                return ResourceManager.GetString("S_PRIVACY_POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Method.
        /// </summary>
        public static string S_PROGRESS_METHOD_TITLE {
            get {
                return ResourceManager.GetString("S_PROGRESS_METHOD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option to display explanation.
        /// </summary>
        public static string S_PROGRESS_METHOD_TOOLTIP {
            get {
                return ResourceManager.GetString("S_PROGRESS_METHOD_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull.
        /// </summary>
        public static string S_PULL_ACTION {
            get {
                return ResourceManager.GetString("S_PULL_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull (Link Target).
        /// </summary>
        public static string S_PULL_ACTION_LINK {
            get {
                return ResourceManager.GetString("S_PULL_ACTION_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Packages.
        /// </summary>
        public static string S_PUSH_PKG {
            get {
                return ResourceManager.GetString("S_PUSH_PKG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not pull file in order to read it..
        /// </summary>
        public static string S_READ_FILE_ERROR {
            get {
                return ResourceManager.GetString("S_READ_FILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Reading File.
        /// </summary>
        public static string S_READ_FILE_ERROR_TITLE {
            get {
                return ResourceManager.GetString("S_READ_FILE_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Redirection.
        /// </summary>
        public static string S_REDIRECTION {
            get {
                return ResourceManager.GetString("S_REDIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following will be removed:
        ///{0}.
        /// </summary>
        public static string S_REM_APK {
            get {
                return ResourceManager.GetString("S_REM_APK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following will be removed:
        ///{0} packages.
        /// </summary>
        public static string S_REM_APK_PLURAL {
            get {
                return ResourceManager.GetString("S_REM_APK_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect Device.
        /// </summary>
        public static string S_REM_DEV {
            get {
                return ResourceManager.GetString("S_REM_DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this device?.
        /// </summary>
        public static string S_REM_DEVICE {
            get {
                return ResourceManager.GetString("S_REM_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0}.
        /// </summary>
        public static string S_REM_DEVICE_TITLE {
            get {
                return ResourceManager.GetString("S_REM_DEVICE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill Emulator.
        /// </summary>
        public static string S_REM_EMU {
            get {
                return ResourceManager.GetString("S_REM_EMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Device.
        /// </summary>
        public static string S_REM_HIST_DEV {
            get {
                return ResourceManager.GetString("S_REM_HIST_DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string S_REPLACE {
            get {
                return ResourceManager.GetString("S_REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All app settings will be reset upon closing the app.
        ///This cannot be undone. Are you sure?.
        /// </summary>
        public static string S_RESET_SETTINGS {
            get {
                return ResourceManager.GetString("S_RESET_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset App Settings.
        /// </summary>
        public static string S_RESET_SETTINGS_TITLE {
            get {
                return ResourceManager.GetString("S_RESET_SETTINGS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart ADB Now.
        /// </summary>
        public static string S_RESTART_ADB_NOW {
            get {
                return ResourceManager.GetString("S_RESTART_ADB_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart app for changes to take effect.
        /// </summary>
        public static string S_RESTART_APP {
            get {
                return ResourceManager.GetString("S_RESTART_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Later.
        /// </summary>
        public static string S_RESTART_LATER {
            get {
                return ResourceManager.GetString("S_RESTART_LATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string S_RESTORE_ACTION {
            get {
                return ResourceManager.GetString("S_RESTORE_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore All Items.
        /// </summary>
        public static string S_RESTORE_ALL {
            get {
                return ResourceManager.GetString("S_RESTORE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Conflicts.
        /// </summary>
        public static string S_RESTORE_CONF_TITLE {
            get {
                return ResourceManager.GetString("S_RESTORE_CONF_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root access cannot be enabled on selected device..
        /// </summary>
        public static string S_ROOT_FORBID {
            get {
                return ResourceManager.GetString("S_ROOT_FORBID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Access.
        /// </summary>
        public static string S_ROOT_FORBID_TITLE {
            get {
                return ResourceManager.GetString("S_ROOT_FORBID_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        public static string S_SEARCH_SETTINGS {
            get {
                return ResourceManager.GetString("S_SEARCH_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search View.
        /// </summary>
        public static string S_SEARCH_VIEW {
            get {
                return ResourceManager.GetString("S_SEARCH_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See terms.
        /// </summary>
        public static string S_SEE_TERMS {
            get {
                return ResourceManager.GetString("S_SEE_TERMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ADB Path.
        /// </summary>
        public static string S_SELECT_ADB_PATH {
            get {
                return ResourceManager.GetString("S_SELECT_ADB_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files to push.
        /// </summary>
        public static string S_SELECT_FILE_PUSH {
            get {
                return ResourceManager.GetString("S_SELECT_FILE_PUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files to push into {0}.
        /// </summary>
        public static string S_SELECT_FILE_PUSH_DESTINATION {
            get {
                return ResourceManager.GetString("S_SELECT_FILE_PUSH_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folders to push.
        /// </summary>
        public static string S_SELECT_FOLDER_PUSH {
            get {
                return ResourceManager.GetString("S_SELECT_FOLDER_PUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folders to push into {0}.
        /// </summary>
        public static string S_SELECT_FOLDER_PUSH_DESTINATION {
            get {
                return ResourceManager.GetString("S_SELECT_FOLDER_PUSH_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Progress Method:.
        /// </summary>
        public static string S_SELECT_PROGRESS_METHOD {
            get {
                return ResourceManager.GetString("S_SELECT_PROGRESS_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Animations.
        /// </summary>
        public static string S_SETTINGS_ANIMATION {
            get {
                return ResourceManager.GetString("S_SETTINGS_ANIMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable APK Handling.
        /// </summary>
        public static string S_SETTINGS_APK {
            get {
                return ResourceManager.GetString("S_SETTINGS_APK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Open For Browsing.
        /// </summary>
        public static string S_SETTINGS_AUTO_OPEN {
            get {
                return ResourceManager.GetString("S_SETTINGS_AUTO_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Enable Root.
        /// </summary>
        public static string S_SETTINGS_AUTO_ROOT {
            get {
                return ResourceManager.GetString("S_SETTINGS_AUTO_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Compact View.
        /// </summary>
        public static string S_SETTINGS_COMPACT_VIEW {
            get {
                return ResourceManager.GetString("S_SETTINGS_COMPACT_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Folder.
        /// </summary>
        public static string S_SETTINGS_DEFAULT_FOLDER {
            get {
                return ResourceManager.GetString("S_SETTINGS_DEFAULT_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Hardware Acceleration.
        /// </summary>
        public static string S_SETTINGS_DISABLE_HW {
            get {
                return ResourceManager.GetString("S_SETTINGS_DISABLE_HW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string S_SETTINGS_DOUBLE_CLICK_NONE {
            get {
                return ResourceManager.GetString("S_SETTINGS_DOUBLE_CLICK_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In Editor.
        /// </summary>
        public static string S_SETTINGS_DOUBLE_CLICK_OPEN {
            get {
                return ResourceManager.GetString("S_SETTINGS_DOUBLE_CLICK_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull To Default Folder.
        /// </summary>
        public static string S_SETTINGS_DOUBLE_CLICK_PULL {
            get {
                return ResourceManager.GetString("S_SETTINGS_DOUBLE_CLICK_PULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Command Log.
        /// </summary>
        public static string S_SETTINGS_ENABLE_LOG {
            get {
                return ResourceManager.GetString("S_SETTINGS_ENABLE_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable mDNS.
        /// </summary>
        public static string S_SETTINGS_ENABLE_MDNS {
            get {
                return ResourceManager.GetString("S_SETTINGS_ENABLE_MDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Recycle Bin.
        /// </summary>
        public static string S_SETTINGS_ENABLE_TRASH {
            get {
                return ResourceManager.GetString("S_SETTINGS_ENABLE_TRASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable File Explorer Monitoring.
        /// </summary>
        public static string S_SETTINGS_EXPLORER_MONITORING {
            get {
                return ResourceManager.GetString("S_SETTINGS_EXPLORER_MONITORING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Fluent Styles.
        /// </summary>
        public static string S_SETTINGS_FLUENT {
            get {
                return ResourceManager.GetString("S_SETTINGS_FLUENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string S_SETTINGS_GROUP_DEVICE {
            get {
                return ResourceManager.GetString("S_SETTINGS_GROUP_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Double Click.
        /// </summary>
        public static string S_SETTINGS_GROUP_DOUBLE_CLICK {
            get {
                return ResourceManager.GetString("S_SETTINGS_GROUP_DOUBLE_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives &amp; Features.
        /// </summary>
        public static string S_SETTINGS_GROUP_DRIVES {
            get {
                return ResourceManager.GetString("S_SETTINGS_GROUP_DRIVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        public static string S_SETTINGS_GROUP_EXPLORER {
            get {
                return ResourceManager.GetString("S_SETTINGS_GROUP_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        public static string S_SETTINGS_GROUP_GRAPHICS {
            get {
                return ResourceManager.GetString("S_SETTINGS_GROUP_GRAPHICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string S_SETTINGS_GROUP_THEME {
            get {
                return ResourceManager.GetString("S_SETTINGS_GROUP_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Directories.
        /// </summary>
        public static string S_SETTINGS_GROUP_WORK_DIRS {
            get {
                return ResourceManager.GetString("S_SETTINGS_GROUP_WORK_DIRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hidden Items.
        /// </summary>
        public static string S_SETTINGS_HIDDEN_ITEMS {
            get {
                return ResourceManager.GetString("S_SETTINGS_HIDDEN_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Media Rescan On Push.
        /// </summary>
        public static string S_SETTINGS_MEDIA_RESCAN {
            get {
                return ResourceManager.GetString("S_SETTINGS_MEDIA_RESCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override ADB Path.
        /// </summary>
        public static string S_SETTINGS_OVERRIDE_ADB {
            get {
                return ResourceManager.GetString("S_SETTINGS_OVERRIDE_ADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Simultaneous Operations.
        /// </summary>
        public static string S_SETTINGS_PARALLEL_OPERATIONS {
            get {
                return ResourceManager.GetString("S_SETTINGS_PARALLEL_OPERATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll For Battery Status.
        /// </summary>
        public static string S_SETTINGS_POLL_BATTERY {
            get {
                return ResourceManager.GetString("S_SETTINGS_POLL_BATTERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll For Devices.
        /// </summary>
        public static string S_SETTINGS_POLL_DEVICES {
            get {
                return ResourceManager.GetString("S_SETTINGS_POLL_DEVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll For Drives.
        /// </summary>
        public static string S_SETTINGS_POLL_DRIVES {
            get {
                return ResourceManager.GetString("S_SETTINGS_POLL_DRIVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Manually Connected Devices.
        /// </summary>
        public static string S_SETTINGS_SAVE_DEVICES {
            get {
                return ResourceManager.GetString("S_SETTINGS_SAVE_DEVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show File Name Extensions.
        /// </summary>
        public static string S_SETTINGS_SHOW_EXTENSIONS {
            get {
                return ResourceManager.GetString("S_SETTINGS_SHOW_EXTENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Splash Screen.
        /// </summary>
        public static string S_SETTINGS_SPLASH {
            get {
                return ResourceManager.GetString("S_SETTINGS_SPLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Polling On Push/Pull.
        /// </summary>
        public static string S_SETTINGS_STOP_ON_SYNC {
            get {
                return ResourceManager.GetString("S_SETTINGS_STOP_ON_SYNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show System Apps.
        /// </summary>
        public static string S_SETTINGS_SYSTEM_APPS {
            get {
                return ResourceManager.GetString("S_SETTINGS_SYSTEM_APPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string S_SETTINGS_THEME_DARK {
            get {
                return ResourceManager.GetString("S_SETTINGS_THEME_DARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Default.
        /// </summary>
        public static string S_SETTINGS_THEME_DEFAULT {
            get {
                return ResourceManager.GetString("S_SETTINGS_THEME_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string S_SETTINGS_THEME_LIGHT {
            get {
                return ResourceManager.GetString("S_SETTINGS_THEME_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string S_SETTINGS_TITLE {
            get {
                return ResourceManager.GetString("S_SETTINGS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string S_SETTINGS_UPDATES {
            get {
                return ResourceManager.GetString("S_SETTINGS_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string S_SKIP {
            get {
                return ResourceManager.GetString("S_SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Explorer Monitoring:.
        /// </summary>
        public static string S_SPLASH_MONITORING_TITLE {
            get {
                return ResourceManager.GetString("S_SPLASH_MONITORING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string S_UNINSTALL {
            get {
                return ResourceManager.GetString("S_UNINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of the selected files cannot be created under a Windows drive root..
        /// </summary>
        public static string S_WIN_ROOT_ILLEGAL {
            get {
                return ResourceManager.GetString("S_WIN_ROOT_ILLEGAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull To Windows Drive Root.
        /// </summary>
        public static string S_WIN_ROOT_ILLEGAL_TITLE {
            get {
                return ResourceManager.GetString("S_WIN_ROOT_ILLEGAL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not push file back to device..
        /// </summary>
        public static string S_WRITE_FILE_ERROR {
            get {
                return ResourceManager.GetString("S_WRITE_FILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Writing File.
        /// </summary>
        public static string S_WRITE_FILE_ERROR_TITLE {
            get {
                return ResourceManager.GetString("S_WRITE_FILE_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Launch if ADB is already authorized in WSA.
        ///To approve ADB, open WSA advanced settings..
        /// </summary>
        public static string S_WSA_LAUNCH {
            get {
                return ResourceManager.GetString("S_WSA_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch WSA in background.
        /// </summary>
        public static string S_WSA_PKG_TIP {
            get {
                return ResourceManager.GetString("S_WSA_PKG_TIP", resourceCulture);
            }
        }
    }
}
