//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB_Explorer.Properties {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADB_Explorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to wts.ItemName.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellGoBackButton.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellHamburgerButtonName.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        public static string ExplorerPageTitle {
            get {
                return ResourceManager.GetString("ExplorerPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        public static string ShellExplorerPage {
            get {
                return ResourceManager.GetString("ShellExplorerPage", resourceCulture);
            }
        }
    
        /// <summary>
            ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
            /// </summary>
            public static string SettingsPageAboutText {
                get {
                    return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to About this application.
            /// </summary>
            public static string SettingsPageAboutTitle {
                get {
                    return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Choose Theme.
            /// </summary>
            public static string SettingsPageChooseThemeText {
                get {
                    return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Personalization.
            /// </summary>
            public static string SettingsPagePersonalizationTitle {
                get {
                    return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Privacy Statement.
            /// </summary>
            public static string SettingsPagePrivacyStatementText {
                get {
                    return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Dark.
            /// </summary>
            public static string SettingsPageRadioButtonDarkTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Light.
            /// </summary>
            public static string SettingsPageRadioButtonLightTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Default.
            /// </summary>
            public static string SettingsPageRadioButtonWindowsDefaultTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
                }
            }
    
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
    }
}
